Feature/flinkster cab rework
dennispost/1BahnQL pull request #25
Opened 2017-07-19 18:56 UTC by dennispost

2017-07-19 19:04 UTC, dennispost commented
Todo: Create separate Area Model

2017-07-19 19:07 UTC, dennispost commented
@lightsprint09 How can we use this https://github.com/ghengeveld/graphql-geojson to support GeoJSON polygons?

2017-07-19 19:27 UTC, lightsprint09 commented
Good question build our own type

2017-07-19 19:41 UTC, dennispost commented
@lightsprint09 this module provides a MultiPolygonObject already (see https://github.com/ghengeveld/graphql-geojson-demo/blob/master/src/schema.js). Is there a way to use this in our 'GraphQL schema language' or do we need to rebuild our schema?

2017-07-20 06:29 UTC, lightsprint09 requested changes

2017-07-20 06:29 UTC, lightsprint09 commented on Flinkster/FlinksterBike.js
>    constructor(att) {
rename parameter `att ` to attributes

2017-07-20 06:29 UTC, lightsprint09 commented on Flinkster/FlinksterCar.js
> +  constructor(att) {
rename parameter `att ` to attributes

2017-07-20 06:29 UTC, lightsprint09 commented on Flinkster/FlinksterCar.js
> +    this.cdPlayer = access(equipment, 'cdPlayer');
try `if (!equipment) {
return
}`

2017-07-20 06:29 UTC, lightsprint09 commented on Flinkster/FlinksterLoader.js
> +  nearbyBikes(latitude, longitude, radius, count, offset) {
duplicated with nearbyCars

2017-07-20 06:29 UTC, lightsprint09 commented on FlinksterParkingArea.js
> +      for (const p of parkingArea.geometry.position.coordinates) {
remove

2017-07-20 06:29 UTC, lightsprint09 commented on schema.js
> +    stations (radius: Int = 10000, count: Int = 10, offset: Int = 0): [Station]!
Mark Elements inside of an array as non optional

2017-07-20 08:20 UTC, merged