Update to support new DB BahnPark API
dennispost/1BahnQL pull request #35
Opened 2017-07-24 15:36 UTC by dennispost

2017-07-24 21:41 UTC, dennispost commented
@lightsprint09 https://github.com/dbsystel/1BahnQL/blob/feature/Update_Parkingspaces_for_new_API/test/Parkingspace/ParkingspaceLoaderMock.js#L18 Should we remove this filter logic from loader?

2017-07-25 05:55 UTC, lightsprint09 commented
Yes remove it

2017-07-25 06:07 UTC, lightsprint09 requested changes
Looks very good. I like the tests 👍

2017-07-25 06:07 UTC, lightsprint09 commented on Parkingspace/Parkingspace.js
>  const fetch = require('node-fetch');
this should not be needed

2017-07-25 06:07 UTC, lightsprint09 commented on Parkingspace/Parkingspace.js
> +    this.clearanceWidth =  access(space, 'spaceInfo.clearanceWidth');
after `=`there are 2 spaces

2017-07-25 06:07 UTC, lightsprint09 commented on Parkingspace/ParkingspaceLoader.js
> +      .then(result => result);
this is not needed

2017-07-25 06:07 UTC, lightsprint09 commented on Parkingspace/ParkingspaceLoader.js
> +    const url = `${baseURL}/spaces?limit=100`;
why do we use 100 asa limit here while using 1000 for spacesAtStation

2017-07-25 06:07 UTC, lightsprint09 commented on schema.js
> +    type: String
can type be an enum

2017-07-25 06:07 UTC, lightsprint09 commented on schema.js
> +    isOutOfService: Boolean
Boolean should not be optional... I am not sure if this is possible here

2017-07-25 06:07 UTC, lightsprint09 commented on test/Parkingspace/testParkingspaceService.js
> +  it.skip('parkingspaceBySpaceId with wrong spaceID should return null', () => {
what does `it.skip` does?

2017-07-27 13:55 UTC, dennispost commented on schema.js
> +    type: String
Maybe, but its not documented so I have no clue wich types do exist

2017-07-27 13:55 UTC, dennispost commented on test/Parkingspace/testParkingspaceService.js
> +  it.skip('parkingspaceBySpaceId with wrong spaceID should return null', () => {
it skips a test ;-)

2017-08-01 10:33 UTC, merged