[WIP] Error handling
dennispost/1BahnQL pull request #36
Opened 2017-07-25 06:22 UTC by lightsprint09

2017-07-27 22:19 UTC, dennispost requested changes

2017-07-27 22:19 UTC, dennispost commented on Station/Station.js
>      this.primaryEvaId = station.evaNumbers.filter(eva => eva.isMain)[0].number;
It is possible, that a station does not have any evaNumbers. Therefore you have to check for existence of `[0]`. Eg. `this.primaryEvaId = access(station.evaNumbers.filter(eva => eva.isMain)[0],'number');`

2017-07-27 22:19 UTC, dennispost commented on Station/Station.js
> +    let ril100Identifiers = (station.ril100Identifiers || []).filter(ril => ril.isMain)[0]
Same as evaNumbers: check for existence of [0].

2017-07-27 22:19 UTC, dennispost commented on Station/Station.js
> +    this.hasSteamPermission = (ril100Identifiers || {}).hasSteamPermission;
hasSteamPermission is non-nullable

2017-07-28 06:58 UTC, lightsprint09 commented on Station/Station.js
> +    let ril100Identifiers = (station.ril100Identifiers || []).filter(ril => ril.isMain)[0]
I think there is always an evaId

2017-08-01 11:06 UTC, merged